### ISSUE TITLE
Hi, is there any documentation for the use of this firmware?

### ISSUE THREAD

**Issue by shuaiger** [Domochip/WirelessRGBW#1]
Hi, is there any documentation for the use of this firmware?

BTW, could you please add support to RGBWW (model [LC11](https://www.banggood.com/ARILUX-AL-LC11-Super-Mini-LED-WIFI-APP-Controller-RF-Remote-Control-For-RGBWW-LED-Strip-DC9-28V-p-1085112.html?cur_warehouse=CN))?

**Comment by Domochip** [comment]
Removal of this project, Tasmota is already able to do this function
